### PR TITLE
Use PHP 8 Observer API if available

### LINKED ISSUE #74: Add generic instrumentation using Observer API for PHP 8.0+
The Observer API was introduced in PHP 8.0+ which is designed to do exactly what we need, but only from PHP 8.0 onwards. For PHP 7.1 to 7.4, see #73.

Example implementation here: https://github.com/SammyK/observer/blob/master/observer.c

Basically, the first time a function is called, we decide whether to add our observer handlers, which means we only "opt in" to functions we're interested in, which is ideal.

More info from PHP Internals News podcast: https://phpinternals.news/68

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #74

### CODE REVIEW

**Comment by asgrim** [comment]
@remicollet is it possible for you to run a test of this branch (`observer-api-php8-client`) on your vast CI matrix that always seems to catch weird things please?

**Comment by remicollet** [comment]
> @remicollet is it possible for you to run a test of this branch (`observer-api-php8-client`) on your vast CI matrix that always seems to catch weird things please?

Seems OK.
Test suite passes with 8.0.7RC1

**Comment by asgrim** [comment]
> > @remicollet is it possible for you to run a test of this branch (`observer-api-php8-client`) on your vast CI matrix that always seems to catch weird things please?
> 
> Seems OK.
> Test suite passes with 8.0.7RC1

Thank you so much! :)

**Comment by remicollet** [comment]
Also run more tests (nearly the full matrix)

* PHP 7.1, 7.2, 7.3, 7.4 and 8.0
* Fedora 32 to 34
* RHEL 7 to 8

Build and test suite OK everywhere.

**Comment by asgrim** [comment]
> Also run more tests (nearly the full matrix)
> 
>     * PHP 7.1, 7.2, 7.3, 7.4 and 8.0
> 
>     * Fedora 32 to 34
> 
>     * RHEL 7 to 8
> 
> 
> Build and test suite OK everywhere.

Thanks @remicollet - really appreciate it!

**Pull request merged**
